// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file example/example.proto (package example, syntax proto3)
/* eslint-disable */

import { createEnumType } from "../src/enum.js";
import type { MessageType } from "../src/message.js";
import { createMessageType } from "../src/message.js";
import { ScalarType } from "../src/scalar.js";
import { Timestamp } from "../src/google/protobuf/timestamp.pb.js";
import type { PartialFieldInfo } from "../src/field.js";

export const protobufPackage = "example";

/**
 * ExampleEnum is an example enumeration.
 *
 * @generated from enum example.ExampleEnum
 */
export enum ExampleEnum {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: FIRST = 1;
   */
  FIRST = 1,

  /**
   * @generated from enum value: SECOND = 2;
   */
  SECOND = 2,
}

export const ExampleEnum_Enum = /* @__PURE__ */ createEnumType(
  "example.ExampleEnum",
  [
    [0, "UNKNOWN"],
    [1, "FIRST"],
    [2, "SECOND"],
  ],
);

/**
 * EchoMsg is the message body for Echo.
 *
 * @generated from message example.EchoMsg
 */
export interface EchoMsg {
  /**
   * @generated from field: string body = 1;
   */
  body?: string;
  /**
   * @generated from field: google.protobuf.Timestamp ts = 2;
   */
  ts?: Date;
  /**
   * @generated from field: repeated google.protobuf.Timestamp timestamps = 5;
   */
  timestamps?: Date[];

  /**
   * @generated from oneof example.EchoMsg.demo
   */
  demo?:
    | {
        value?: undefined;
        case: undefined;
      }
    | {
        /**
         * @generated from field: example.ExampleEnum example_enum = 3;
         */
        value: ExampleEnum;
        case: "exampleEnum";
      }
    | {
        /**
         * @generated from field: string example_string = 4;
         */
        value: string;
        case: "exampleString";
      };
}

export const EchoMsg: MessageType<EchoMsg> = /* @__PURE__ */ createMessageType({
  typeName: "example.EchoMsg",
  fields: [
    { no: 1, name: "body", kind: "scalar", T: ScalarType.STRING },
    { no: 2, name: "ts", kind: "message", T: () => Timestamp },
    {
      no: 3,
      name: "example_enum",
      kind: "enum",
      T: ExampleEnum_Enum,
      oneof: "demo",
    },
    {
      no: 4,
      name: "example_string",
      kind: "scalar",
      T: ScalarType.STRING,
      oneof: "demo",
    },
    {
      no: 5,
      name: "timestamps",
      kind: "message",
      T: () => Timestamp,
      repeated: true,
    },
  ] satisfies readonly PartialFieldInfo[],
  packedByDefault: true,
});
