// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file example/example.proto (package example, syntax proto3)
/* eslint-disable */

import { createEnumType, createMessageType, Message, MessageType, PartialFieldInfo } from "@aptre/protobuf-es-lite";
import { Timestamp } from "@bufbuild/protobuf";

export const protobufPackage = "example";

/**
 * ExampleEnum is an example enumeration.
 *
 * @generated from enum example.ExampleEnum
 */
export enum ExampleEnum {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: FIRST = 1;
   */
  FIRST = 1,

  /**
   * @generated from enum value: SECOND = 2;
   */
  SECOND = 2,
}

// ExampleEnum_Enum is the enum type for ExampleEnum.
export const ExampleEnum_Enum = createEnumType("example.ExampleEnum", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "FIRST" },
  { no: 2, name: "SECOND" },
]);

/**
 * EchoMsg is the message body for Echo.
 *
 * @generated from message example.EchoMsg
 */
export interface EchoMsg extends Message<EchoMsg> {
  /**
   * @generated from field: string body = 1;
   */
  body?: string;
  /**
   * @generated from field: google.protobuf.Timestamp ts = 2;
   */
  ts?: Timestamp;

  /**
   * @generated from oneof example.EchoMsg.demo
   */
  demo?: {
    value?: undefined,
    case: undefined
  } | {
    /**
     * @generated from field: example.ExampleEnum example_enum = 3;
     */
    value: ExampleEnum;
    case: "exampleEnum";
  } | {
    /**
     * @generated from field: string example_string = 4;
     */
    value: string;
    case: "exampleString";
  };

}

export const EchoMsg: MessageType<EchoMsg> = createMessageType(
  {
    typeName: "example.EchoMsg",
    fields: [
        { no: 1, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "ts", kind: "message", T: Timestamp },
        { no: 3, name: "example_enum", kind: "enum", T: ExampleEnum_Enum, oneof: "demo" },
        { no: 4, name: "example_string", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "demo" },
    ] as readonly PartialFieldInfo[],
    packedByDefault: true,
  },
);

