//

// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file example/example.proto (package example, syntax proto3)
/* eslint-disable */

//

import type { MessageType, PartialFieldInfo } from "@aptre/protobuf-es-lite";
import { createEnumType, createMessageType, Message, Timestamp } from "@aptre/protobuf-es-lite";

export const protobufPackage = "example";

/**
 * ExampleEnum is an example enumeration.
 *
 *
 * @generated from enum example.ExampleEnum
 */
export enum ExampleEnum {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: FIRST = 1;
   */
  FIRST = 1,

  /**
   * @generated from enum value: SECOND = 2;
   */
  SECOND = 2,
}

// ExampleEnum_Enum is the enum type for ExampleEnum.
export const ExampleEnum_Enum = createEnumType("example.ExampleEnum", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "FIRST" },
  { no: 2, name: "SECOND" },
]);

/**
 * EchoMsg is the message body for Echo.
 *
 *
 * @generated from message example.EchoMsg
 */
export type EchoMsg = Message<{
  /**
   * @generated from field: string body = 1 [packed = false, default = "", jstype = JS_NORMAL];
   */
  body?: string;
  /**
   * @generated from field: google.protobuf.Timestamp ts = 2 [packed = false, default = , jstype = JS_NORMAL];
   */
  ts?: Timestamp;
  /**
   * @generated from field: example.ExampleEnum example_enum = 3 [packed = false, default = , jstype = JS_NORMAL];
   */
  exampleEnum?: ExampleEnum;
  /**
   * @generated from field: string example_string = 4 [packed = false, default = "", jstype = JS_NORMAL];
   */
  exampleString?: string;
  /**
   * @generated from field: repeated google.protobuf.Timestamp timestamps = 5 [packed = false, default = , jstype = JS_NORMAL];
   */
  timestamps?: Timestamp[];

}>;

export const EchoMsg: MessageType<EchoMsg> = createMessageType(
  {
    typeName: "example.EchoMsg",
    fields: [
        { no: 1, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "ts", kind: "message", T: () => Timestamp },
        { no: 3, name: "example_enum", kind: "enum", T: ExampleEnum_Enum },
        { no: 4, name: "example_string", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "timestamps", kind: "message", T: () => Timestamp, repeated: true },
    ] as readonly PartialFieldInfo[],
    packedByDefault: true,
  },
);

